// Palabras del juego "El Completado", con imagen real de Minecraft.
// syl = división en sílabas, usada por el botón de escuchar por sílabas.
// Agregá o quitá entradas acá. La imagen sale de ../../assets/img/
const WORDS = [
  { word: "TIERRA", img: "tierra.png", syl: ["TIE", "RRA"] },
  { word: "PIEDRA", img: "piedra.png", syl: ["PIE", "DRA"] },
  { word: "ARENA", img: "arena.png", syl: ["A", "RE", "NA"] },
  { word: "AGUA", img: "agua.png", syl: ["A", "GUA"] },
  { word: "LAVA", img: "lava.png", syl: ["LA", "VA"] },
  { word: "FUEGO", img: "fuego.gif", syl: ["FUE", "GO"] },
  { word: "COFRE", img: "cofre.gif", syl: ["CO", "FRE"] },
  { word: "PUERTA", img: "puerta.png", syl: ["PUER", "TA"] },
  { word: "CAMA", img: "cama.png", syl: ["CA", "MA"] },
  { word: "LIBRO", img: "libro.png", syl: ["LI", "BRO"] },
  { word: "PAN", img: "pan.png", syl: ["PAN"] },
  { word: "MANZANA", img: "manzana.png", syl: ["MAN", "ZA", "NA"] },
  { word: "GATO", img: "gato.png", syl: ["GA", "TO"] },
  { word: "VACA", img: "vaca.png", syl: ["VA", "CA"] },
  { word: "CERDO", img: "cerdo.png", syl: ["CER", "DO"] },
  { word: "OVEJA", img: "oveja.png", syl: ["O", "VE", "JA"] },
  { word: "ANTORCHA", img: "antorcha.gif", syl: ["AN", "TOR", "CHA"] },
  { word: "DIAMANTE", img: "diamante.png", syl: ["DIA", "MAN", "TE"] },
  { word: "ORO", img: "oro.png", syl: ["O", "RO"] },
  { word: "HIERRO", img: "hierro.png", syl: ["HIE", "RRO"] },
  { word: "CARBON", img: "carbon.png", syl: ["CAR", "BON"] },
  { word: "HACHA", img: "hacha.png", syl: ["HA", "CHA"] },
  { word: "PALA", img: "pala.png", syl: ["PA", "LA"] },
  { word: "PICO", img: "pico.png", syl: ["PI", "CO"] },
  { word: "VIDRIO", img: "vidrio.png", syl: ["VI", "DRIO"] },
  { word: "BARCO", img: "barco.png", syl: ["BAR", "CO"] },
  { word: "ZANAHORIA", img: "zanahoria.png", syl: ["ZA", "NA", "HO", "RIA"] },
  { word: "MELON", img: "melon.png", syl: ["ME", "LON"] },
  { word: "CALABAZA", img: "calabaza.png", syl: ["CA", "LA", "BA", "ZA"] },
  { word: "TRONCO", img: "tronco.png", syl: ["TRON", "CO"] },
  { word: "ZOMBI", img: "zombi.png", syl: ["ZOM", "BI"] },
  { word: "ESQUELETO", img: "esqueleto.png", syl: ["ES", "QUE", "LE", "TO"] },
  { word: "ARAÑA", img: "arana.png", syl: ["A", "RA", "ÑA"] },
  { word: "ESMERALDA", img: "esmeralda.png", syl: ["ES", "ME", "RAL", "DA"] },
  { word: "CUBO", img: "cubo.png", syl: ["CU", "BO"] },
  { word: "LINTERNA", img: "linterna.gif", syl: ["LIN", "TER", "NA"] },
  { word: "ESCALERA", img: "escalera.png", syl: ["ES", "CA", "LE", "RA"] },
];
